name: Win2025 Tailscale noVNC-Standalone
on:
  workflow_dispatch
jobs:
  novnc-host:
    runs-on: windows-2025
    timeout-minutes: 350
    steps:
      - name: 系统基础配置 + 放行端口
        run: |
          $securePwd = ConvertTo-SecureString "Win@202566" -AsPlainText -Force
          Set-LocalUser -Name runneradmin -Password $securePwd
          New-NetFirewallRule -DisplayName "VNC-5900" -Direction Inbound -LocalPort 5900 -Protocol TCP -Action Allow
          New-NetFirewallRule -DisplayName "noVNC-6080" -Direction Inbound -LocalPort 6080 -Protocol TCP -Action Allow

      - name: 安装 Tailscale
        run: winget install Tailscale.Tailscale --silent --accept-source-agreements --accept-package-agreements

      - name: Tailscale 接入组网
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey $env:TS_AUTHKEY
          Start-Sleep 15

      - name: 安装Python
        run: winget install Python.Python.3.12 --silent --accept-source-agreements --accept-package-agreements

      - name: 下载独立免安装 UltraVNC 压缩包
        run: |
          $zipUrl = "https://github.com/rdesktop/rdesktop/releases/download/v1.9.0/ultravnc_x64_portable.zip"
          $zipPath = "$env:TEMP\uvnc_portable.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
          Expand-Archive -Path $zipPath -DestinationPath C:\uvnc -Force
          Start-Sleep 6

      - name: 启动便携版 winvnc
        run: |
          Start-Process "C:\uvnc\winvnc.exe" -ArgumentList "-run"
          Start-Sleep 5

      - name: 下载 noVNC
        run: |
          git clone https://github.com/novnc/noVNC.git C:\noVNC
          Start-Sleep 3

      - name: 安装websockify
        run: pip install websockify

      - name: 启动noVNC代理
        run: |
          cd C:\noVNC
          Start-Process python ".\utils\websockify.py 6080 localhost:5900"

      - name: 持续常驻
        run: |
          while($true) {
            Start-Sleep 60
          }
