name: Win2022 ChmlFrp RDP
on:
  workflow_dispatch
jobs:
  rdp-host:
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: 开启RDP远程桌面 + 设置账号密码 + 放行防火墙
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Restart-Service TermService -Force
          $securePwd = ConvertTo-SecureString "Win@202566" -AsPlainText -Force
          Set-LocalUser -Name runneradmin -Password $securePwd
          New-NetFirewallRule -DisplayName "AllowRDP" -Direction Inbound -LocalPort 3389 -Protocol TCP -Action Allow

      - name: 启动Windows音频服务
        run: |
          Set-Service Audiosrv -StartupType Automatic
          Start-Service Audiosrv -ErrorAction SilentlyContinue

      - name: 下载frp原版客户端（Github，海外可访问）
        run: |
          $dlPath = "C:\Users\runneradmin\Downloads\frp.zip"
          Invoke-WebRequest -Uri "https://github.com/fatedier/frp/releases/download/v0.51.2/frp_0.51.2_windows_386.zip" -OutFile $dlPath

      - name: 解压frp
        run: |
          $zipFile = "C:\Users\runneradmin\Downloads\frp.zip"
          $extractDir = "C:\Users\runneradmin\Downloads\"
          Expand-Archive -Path $zipFile -DestinationPath $extractDir -Force

      - name: 生成frpc.ini
        run: >
          $iniPath = "C:\Users\runneradmin\Downloads\frp_0.51.2_windows_386\frpc.ini";
          '[common]
          server_addr = 47.109.152.106
          server_port = 7000
          tls_enable = false
          user = qxCHUlNnkWPhLcQ9pXYuIDiH
          token = ChmlFrpToken

          [am4TrUiZ]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 3389
          remote_port = 33077' | Out-File $iniPath -Encoding utf8

      - name: 查看frpc.ini内容
        run: |
          cat "C:\Users\runneradmin\Downloads\frp_0.51.2_windows_386\frpc.ini"

      - name: 修改RDP注册表关闭NLA
        run: |
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /v SecurityLayer /t REG_DWORD /d 0 /f
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /v UserAuthentication /t REG_DWORD /d 0 /f

      - name: 启动frpc常驻
        run: |
          cd C:\Users\runneradmin\Downloads\frp_0.51.2_windows_386
          .\frpc.exe
          while($true){Start-Sleep 600}
