name: Win2025 noVNC网页远程桌面
on:
  workflow_dispatch
jobs:
  novnc-host:
    runs-on: windows-2025
    timeout-minutes: 340
    steps:
      - name: 创建远程账号
        run: |
          $securePwd = ConvertTo-SecureString "Win@202566" -AsPlainText -Force
          Set-LocalUser -Name runneradmin -Password $securePwd
          $memberCheck = Get-LocalGroupMember -Group Administrators -Member runneradmin -ErrorAction SilentlyContinue
          if(-not $memberCheck){
            Add-LocalGroupMember -Group Administrators -Member runneradmin
          }

      - name: 放行防火墙端口
        run: |
          New-NetFirewallRule -DisplayName "VNC-5900" -Direction Inbound -LocalPort 5900 -Protocol TCP -Action Allow -ErrorAction SilentlyContinue
          New-NetFirewallRule -DisplayName "noVNC-9000" -Direction Inbound -LocalPort 9000 -Protocol TCP -Action Allow -ErrorAction SilentlyContinue

      - name: 安装Tailscale
        run: |
          winget install Tailscale.Tailscale --silent --accept-source-agreements
          cd "C:\Program Files\Tailscale"
          .\tailscale.exe up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: 安装NodeJS
        run: winget install OpenJS.NodeJS.LTS --silent --accept-source-agreements

      - name: 下载安装TigerVNC（Github官方地址，修复源失效问题）
        run: |
          $downloadUrl = "https://github.com/TigerVNC/tigervnc/releases/download/v1.13.0/vnc64-1.13.0.exe"
          $installerPath = "$env:TEMP\vncsetup.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath -UseBasicParsing
          Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait

      - name: 启动 TigerVNC Server
        run: |
          Start-Process "C:\Program Files\TigerVNC\winvnc4.exe" -ArgumentList "-run"
          Start-Sleep 3

      - name: 拉取noVNC
        run: |
          git clone https://github.com/novnc/noVNC.git C:\noVNC
          cd C:\noVNC
          git clone https://github.com/novnc/websockify.git websockify

      - name: 启动noVNC（转发5900 VNC端口）
        run: |
          cd C:\noVNC
          Start-Process node -ArgumentList "websockify/websockify.js --web . 9000 localhost:5900"

      - name: 保持运行
        run: |
          while($true){
            Start-Sleep -Seconds 60
          }
